---
defaults:
  run:
    working-directory: geerlingguy.packer
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
    - name: Check out the codebase.
      uses: actions/checkout@v6
      with:
        path: geerlingguy.packer
    - name: Set up Python 3.
      uses: actions/setup-python@v5.1.1
      with:
        python-version: 3.x
    - name: Install test dependencies.
      run: pip3 install yamllint
    - name: Lint code.
      run: 'yamllint .
=======
      - name: Check out the codebase.
        uses: actions/checkout@v6
        with:
          path: geerlingguy.packer
      - name: Set up Python 3.
        uses: actions/setup-python@v6.1.1
        with:
          python-version: 3.x
      - name: Install test dependencies.
        run: pip3 install yamllint
      - name: Lint code.
        run: 'yamllint .
>>>>>>> 4280189 (Update files using ansible-generator)

          '
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
    - name: Check out the codebase.
      uses: actions/checkout@v6
      with:
        path: geerlingguy.packer
    - name: Set up Python 3.
      uses: actions/setup-python@v5.1.1
      with:
        python-version: 3.x
    - name: Install test dependencies.
      run: pip3 install ansible molecule[docker] docker
    - env:
        ANSIBLE_FORCE_COLOR: '1'
        MOLECULE_DISTRO: ${{ matrix.distro }}
        PY_COLORS: '1'
      name: Run Molecule tests.
      run: molecule test
=======
      - name: Check out the codebase.
        uses: actions/checkout@v6
        with:
          path: geerlingguy.packer
      - name: Set up Python 3.
        uses: actions/setup-python@v6.1.1
        with:
          python-version: 3.x
      - name: Install test dependencies.
        run: pip3 install ansible molecule[docker] docker
      - env:
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
          PY_COLORS: '1'
        name: Run Molecule tests.
        run: molecule test
>>>>>>> 4280189 (Update files using ansible-generator)
    strategy:
      matrix:
        distro:
          - rockylinux8
          - centos7
          - ubuntu2004
          - debian11
name: CI
'on':
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: 0 5 * * 4
